[package]
name = "glimbot"
version = "0.1.0"
authors = ["Nicholas Samson <me@nicksamson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.8.11"
clap = "2.33.0"
serde = "1.0.104"
better-panic = "0.2.0"

thiserror = "1.0.11"
once_cell = "1.3.1"
log = "0.4.8"
fern = "0.5.9"
chrono = "0.4.10"
parking_lot = "0.10.0"
circular-queue = "0.2.3"
pest = "2.1.3"
pest_derive = "2.1.0"
rand = "0.7.3"
[dependencies.libsqlite3-sys]
version = "0.9.1"
features = ["bundled"]

[dependencies.serenity]
version = "0.8.0"

[dependencies.diesel]
version = "1.4.3"
features = ["sqlite", "r2d2"]

[dependencies.regex]
version = "1.3.4"
features = ["std", "perf", "perf-cache", "perf-dfa", "perf-literal", "unicode"]