#  Glimbot - A Discord anti-spam and administration bot.
#  Copyright (C) 2020 Nick Samson

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

[package]
name = "glimbot"
version = "0.2.0"
authors = ["Nick Samson <me@nicksamson.com>"]
edition = "2018"
license = "GPLv3+"
readme = "README.md"
repository = "https://github.com/nes77/glimbot"
description = "A Discord anti-spam and admin bot."
exclude = [".env"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.8.11"
clap = "2.33.0"
serde = "1.0.104"
better-panic = "0.2.0"
thiserror = "1.0.11"
once_cell = "1.3.1"
log = "0.4.8"
chrono = "0.4.10"
parking_lot = "0.10.0"
circular-queue = "0.2.3"
pest = "2.1.3"
pest_derive = "2.1.0"
rand = "0.7.3"
nom = "5.1.1"
num = "0.2.1"
lock_api = "0.3.3"
typemap = "0.3.3"
dotenv = "0.15.0"
dirs = "2.0.2"
failure = "0.1.7"
itertools = "0.9.0"
shell-words = "0.1.0"
lru-cache = "0.1.2"
log4rs = "0.11.0"

[dependencies.rust-embed]
version = "5.5.1"
features = ["interpolate-folder-path", "debug-embed"]

[dependencies.futures]
version = "0.3.4"
features = ["thread-pool"]

[dependencies.rusqlite]
version = "0.22.0"

[dependencies.serenity]
version = "0.8.4"

[dependencies.regex]
version = "1.3.4"
features = ["std", "perf", "perf-cache", "perf-dfa", "perf-literal", "unicode"]

[package.metadata.deb]
depends = "$auto"

[dev-dependencies]
tempdir = "0.3.7"

[features]
default = ["sqlite-bundled", "development"]
development = []
sqlite-bundled = ["rusqlite/bundled"]